import { Afacad_Flux } from "next/font/google";
import { siganaFont } from "./fonts";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import CanvasLoader from "@/3d/canvas-loader";

const afacadFlux = Afacad_Flux({
  variable: "--font-afacad-flux",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${afacadFlux.variable}  ${siganaFont.variable} antialiased`}
      >
        <NavBar />
        <CanvasLoader />
        {children}
      </body>
    </html>
  );
}
